services:
  fintech-frontend:
    build: .
    container_name: fintech-frontend
    depends_on:
      - fintech-backend
    ports:
      - "80:80"
    networks:
      - fintech-net
    restart: unless-stopped
networks:
  fintech-net:
    external: true