server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location /auth/ { proxy_pass http://fintech-backend:8000; }
    location /users/ { proxy_pass http://fintech-backend:8000; }
    location /categories/ { proxy_pass http://fintech-backend:8000; }
    location /movements/ { proxy_pass http://fintech-backend:8000; }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
